In [1]:
import tensorflow as tf

In [2]:
import warnings

In [3]:
tf.__version__

'2.10.0'

In [4]:
import numpy as np
import pandas as pd

In [ ]:
dataset = pd.read_csv(r"C:\Users\thila\Downloads\Churn_Modelling.csv")

In [6]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [7]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [8]:
X = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [9]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [10]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [11]:
X.shape

(10000, 10)

In [12]:
y.shape

(10000,)

In [13]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [1])],remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [15]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [16]:
from sklearn.model_selection import train_test_split
X_train ,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [17]:
dataset.shape

(10000, 14)

In [18]:
import warnings

In [19]:
ann = tf.keras.models.Sequential()

In [20]:
ann.add(tf.keras.layers.Dense(units = 6,activation = 'relu'))

In [21]:
ann.add(tf.keras.layers.Dense(units = 6,activation = 'relu'))

In [22]:
ann.add(tf.keras.layers.Dense(units = 1,activation = 'sigmoid'))

In [23]:
import warnings

In [24]:
ann.compile(optimizer = 'sgd' ,loss = 'binary_crossentropy',metrics = ['accuracy'])

In [25]:
X_train = np.array(X_train).astype(np.float32)
y_train = np.array(y_train).astype(np.float32)

In [26]:
X_test = np.array(X_test).astype(np.float32)
y_test = np.array(y_test).astype(np.float32)

In [27]:
ann.fit(X_train,y_train,batch_size = 32,epochs = 10)

Epoch 1/10
250/250 [==============================] - 2s 4ms/step - loss: 6.2096 - accuracy: 0.7936
Epoch 2/10
250/250 [==============================] - 1s 4ms/step - loss: 0.5443 - accuracy: 0.7960
Epoch 3/10
250/250 [==============================] - 1s 4ms/step - loss: 0.5203 - accuracy: 0.7960
Epoch 4/10
250/250 [==============================] - 1s 4ms/step - loss: 0.5116 - accuracy: 0.7960
Epoch 5/10
250/250 [==============================] - 1s 4ms/step - loss: 0.5083 - accuracy: 0.7960
Epoch 6/10
250/250 [==============================] - 1s 4ms/step - loss: 0.5069 - accuracy: 0.7960
Epoch 7/10
250/250 [==============================] - 1s 4ms/step - loss: 0.5063 - accuracy: 0.7960
Epoch 8/10
250/250 [==============================] - 1s 4ms/step - loss: 0.5061 - accuracy: 0.7960
Epoch 9/10
250/250 [==============================] - 1s 4ms/step - loss: 0.5060 - accuracy: 0.7960
Epoch 10/10
250/250 [==============================] - 1s 4ms/step - loss: 0.5060 - accuracy: 0.7960

In [28]:
y_pred = ann.predict(X_test)
y_pred = (y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)

from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test,y_pred)
print(ac)

63/63 [==============================] - 0s 3ms/step
[[0. 0.]
 [0. 1.]
 [0. 0.]
 ...
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1595    0]
 [ 405    0]]
0.7975
